name: "Shuttle Service Bus"
description: "Shuttle ESB is a free open-source enterprise service bus"

baseurl: "http://shuttle.github.io/shuttle-esb"

paginate: 10

markdown: redcarpet
permalink: pretty
pygments: true

redcarpet:
  extensions: ["tables"]